services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  greeting-service-one:
    build: ./greeting-service-one
    container_name: greeting-service-one
    ports:
      - "9091:9091"

  greeting-service-two:
    build: ./greeting-service-two
    container_name: greeting-service-two
    depends_on:
      - kafka
      - greeting-service-one
    ports:
      - "9092:9092"

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - greeting-service-two
    ports:
      - "8080:8080"
